export default [
	{ id: '1', imageName: 'img1.jpg', tag: 'sushi' },
	{ id: '2', imageName: 'img2.jpg', tag: 'other' },
	{ id: '3', imageName: 'img3.jpg', tag: 'sushi' },
	{ id: '4', imageName: 'img4.jpg', tag: 'sushi' },
	{ id: '5', imageName: 'img5.jpg', tag: 'sushi' },
	{ id: '6', imageName: 'img6.jpg', tag: 'sushi' },
	{ id: '7', imageName: 'img6.jpg', tag: 'sushi' },
	{ id: '8', imageName: 'img8.jpg', tag: 'sushi' },
	{ id: '9', imageName: 'img9.jpg', tag: 'sushi' },
	{ id: '10', imageName: 'img10.jpg', tag: 'sushi' },
	{ id: '11', imageName: 'img11.jpg', tag: 'sushi' },
	{ id: '12', imageName: 'img12.jpg', tag: 'sushi' },
	{ id: '13', imageName: 'img13.jpg', tag: 'kitchen food' },
	{ id: '14', imageName: 'img14.jpg', tag: 'sushi' },
	{ id: '15', imageName: 'img15.jpg', tag: 'sushi' },
	{ id: '16', imageName: 'img16.jpg', tag: 'sushi' },
	{ id: '17', imageName: 'img17.jpg', tag: 'sushi' },
	{ id: '18', imageName: 'img18.jpg', tag: 'sushi' },
	{ id: '19', imageName: 'img19.jpg', tag: 'sushi' },
	{ id: '20', imageName: 'img20.jpg', tag: 'sushi' },
	{ id: '21', imageName: 'img21.jpg', tag: 'sushi' },
	{ id: '22', imageName: 'img22.jpg', tag: 'sushi' },
	{ id: '23', imageName: 'img23.jpg', tag: 'sushi' },
	{ id: '24', imageName: 'img24.jpg', tag: 'sushi' }

];
