export default [
  {
    id: "1",
    imageName: "img1.jpg",
    tag: "appetizers",
    name: "Miso Soup",
    description:
      "Traditional Soy based broth served with tofu, dry seaweed and green onions",
    price: "$1.99",
  },
  {
    id: "2",
    imageName: "img2.jpg",
    tag: "appetizers",
    name: "Edamame",
    description: "Fresh Japanese Soybeans served warm and salted",
    price: "$4.29",
  },
  {
    id: "3",
    imageName: "img3.jpg",
    tag: "appetizers",
    name: "Gyoza",
    description: "5 Pan seared Japanese Pork & Veggie Dumplings",
    price: "$6.59",
  },
  {
    id: "4",
    imageName: "img4.jpg",
    tag: "appetizers",
    name: "Shrimp & Veggie Tempura",
    description:
      "3 Tempura Black Tiger Shrimp served with a variety of Tempura Vegetables",
    price: "$8.59",
  },
  {
    id: "5",
    imageName: "img5.jpg",
    tag: "appetizers",
    name: "Vegetable Tempura",
    description:
      "Tempura carrot, yam, zucchini, onion and squash with tempura dipping sauce",
    price: "$5.99",
  },
  {
    id: "6",
    imageName: "img6.jpg",
    tag: "appetizers",
    name: "Calamari Tempura",
    description: "Japanese Calamari fried in delicate Tempura Batter",
    price: "$8.59",
  },
  {
    id: "7",
    imageName: "img6.jpg",
    tag: "appetizers",
    name: "Garlic Chicken Wings",
    description: "Seasoned and fried Chicken Wings in Garlic Teriyaki Sauce",
    price: "$7.99",
  },
  {
    id: "8",
    imageName: "img8.jpg",
    tag: "appetizers",
    name: "BBQ Shrimp",
    description:
      "Black Tiger Shrimp, wrapped in bacon, grilled in Asian BBQ Sauce",
    price: "$7.99",
  },
  {
    id: "9",
    imageName: "img9.jpg",
    tag: "appetizers",
    name: "Citrus Aoli Prawns",
    description: "Deep fried five prawns served with Citrus Aoli Sauce",
    price: "$7.29",
  },
  {
    id: "10",
    imageName: "img10.jpg",
    tag: "appetizers",
    name: "Asian Lettuce Cup",
    description:
      "Seasoned and spiced tender beef or chicken served with fresh lettuce cup",
    price: "$7.29",
  },
  {
    id: "11",
    imageName: "img11.jpg",
    tag: "appetizers",
    name: "Agedashi Tofu",
    description:
      "Tempura Tofu in soy broth with dry seaweed, fresh ginger and green onions",
    price: "$5.99",
  },
  {
    id: "12",
    imageName: "img12.jpg",
    tag: "appetizers",
    name: "Mussel Shooters",
    description:
      "Traditional Soy based broth served with tofu, dry seaweed and green onions",
    price: "$6.99",
  },
  {
    id: "13",
    imageName: "img13.jpg",
    tag: "appetizers",
    name: "Monkey Brain",
    description: "Tempura mushroom cups stuffed with spicy tuna & diced jalapeno served in wasabi mayo & yuzu",
    price: "$7.59",
  },
  {
    imageName: "img13.jpg",
    tag: "appetizers",
    name: "Steamed White Rice",
    description: "",
    price: "$1.99",
  },
];
