export default [
  {
    id: "29",
    imageName: "img1.jpg",
    tag: "entrees",
    name: "Grilled Chicken Teriyaki",
    description: "Tender grilled Chicken Breast served with Teriyaki sauce",
    price: "$12.99",
  },
  {
    id: "30",
    imageName: "img2.jpg",
    tag: "entrees",
    name: "Chicken Tats",
    description: "Lightly battered Tempura Chicken Breast with Teriyaki glaze",
    price: "$13.99",
  },
  {
    id: "31",
    imageName: "img3.jpg",
    tag: "entrees",
    name: "Sakana Steak",
    description: "The most flavorful cut of Beef Tenderloin grilled to perfection with Vegetable",
    price: "$16.99",
  },
  {
    id: "33",
    imageName: "img1.jpg",
    tag: "entrees",
    name: "Salmon Teriyaki",
    description: "Sashimi grade Salmon served with Teriyaki sauce",
    price: "$16.99",
  },
  {
    id: "34",
    imageName: "img2.jpg",
    tag: "entrees",
    name: "BBQ Baby Back Pork Ribs",
    description: "Baby Back Pork Ribs braised & brushed with Asian BBQ Glaze with French fries",
    price: "$16.99",
  },
  {
    id: "35",
    imageName: "img3.jpg",
    tag: "entrees",
    name: "Pork Katsu",
    description: "Seasoned deep-fried breaded Pork Tenderloin served with Tonkatsu Sauce",
    price: "$14.99",
  },
  {
    id: "33",
    imageName: "img1.jpg",
    tag: "entrees",
    name: "Seafood Tempura",
    description: "2 pieces of Scallops, Calamari, Crab, Shrimp & White Fish Tempura",
    price: "$15.99",
  },
  {
    id: "34",
    imageName: "img2.jpg",
    tag: "entrees",
    name: "Shrimp Tempura",
    description: "6 Black Tiger Shrimp & Seasonal Vegetables prepared in delicate Tempura Batter",
    price: "$15.99",
  },
  {
    id: "36",
    imageName: "img4.jpg",
    tag: "entrees",
    name: "Vegetable Tempura",
    description: "2 pieces of Carrots, Yams, Zucchinis, Onions, Asparagus and Squash Tempura",
    price: "$10.99",
  },
  {
    id: "37",
    imageName: "img3.jpg",
    tag: "entrees",
    name: "Shrimp Tempura Udon",
    description: "Traditional Japanese Soy broth with flour noodles and Shrimp & Veggie Tempura",
    price: "$13.99",
  },
  {
    id: "38",
    imageName: "img4.jpg",
    tag: "entrees",
    name: "Yaki-Soba",
    description: "Pan sautéed Yaki-soba Noodles with your choice of Chicken, Shrimp or Beef",
    price: "$12.99",
  },
];
