export default [
  {
    id: "101",
    imageName: "img1.jpg",
    tag: "lunch_entrees",
    name: "Chicken Teriyaki Donburi",
    description: "Grilled Chicken Teriyaki with Veggie Tempura over Rice",
    price: "$10.99",
  },
  {
    id: "102",
    imageName: "img2.jpg",
    tag: "lunch_entrees",
    name: "Beef Teriyaki Donburi",
    description: "Grilled Steak Teriyaki with Veggie Tempura over Rice",
    price: "$10.99",
  },
  {
    id: "103",
    imageName: "img3.jpg",
    tag: "lunch_entrees",
    name: "Salmon Teriyaki Donburi",
    description: "Grilled Salmon Teriyaki with Veggie Tempura over Rice",
    price: "$10.99",
  },
  {
    id: "104",
    imageName: "img4.jpg",
    tag: "lunch_entrees",
    name: "Tendon",
    description: "4 piece of Shrimp and Veggie Tempura over Rice",
    price: "$10.99",
  },
  {
    id: "105",
    imageName: "img1.jpg",
    tag: "lunch_entrees",
    name: "Chicken Salad",
    description: "Grilled Chicken Teriyaki with mixed greens, cucumber, tomato & orange with Vinaigrette",
    price: "$10.99",
  },
  {
    id: "106",
    imageName: "img2.jpg",
    tag: "lunch_entrees",
    name: "Steak Salad",
    description: "Tender Steak Teriyaki with mixed greens, cucumber, tomato & orange with Vinaigrette",
    price: "$10.99",
  },
  {
    id: "107",
    imageName: "img3.jpg",
    tag: "lunch_entrees",
    name: "Salmon Salad",
    description: "Grilled Salmon Teriyaki with mixed greens, cucumber, tomato & orange with Vinaigrette",
    price: "$10.99",
  },
  {
    id: "108",
    imageName: "img4.jpg",
    tag: "lunch_entrees",
    name: "White Tuna Salad",
    description: "Seared and seasoned Albacore Tuna with mixed green salad, cucumber, avocado",
    price: "$10.99",
  },
  {
    id: "109",
    imageName: "img1.jpg",
    tag: "lunch_entrees",
    name: "Bento Box",
    description: "Served with miso soup or side salad, 4 piece of California roll & steamed rice.",
    price: "$12.99",
  },
];
