export default [
  {
    id: "70",
    imageName: "img1.jpg",
    tag: "maki_sushi",
    name: "Tekka Maki",
    description: "(Tuna roll)",
    price: "$5.99",
  },
  {
    id: "71",
    imageName: "img2.jpg",
    tag: "maki_sushi",
    name: "Sake Maki",
    description: "(Salmon roll)",
    price: "$5.99",
  },
  {
    id: "72",
    imageName: "img3.jpg",
    tag: "maki_sushi",
    name: "Unagi Maki",
    description: "(Eel roll)",
    price: "$6.99",
  },
  {
    id: "74",
    imageName: "img1.jpg",
    tag: "maki_sushi",
    name: "Negihama",
    description: "(Yellowtail roll)",
    price: "$5.99",
  },
  {
    id: "75",
    imageName: "img2.jpg",
    tag: "maki_sushi",
    name: "California Roll",
    description: "Crab, cucumber &avocado",
    price: "$6.29",
  },
  {
    id: "76",
    imageName: "img3.jpg",
    tag: "maki_sushi",
    name: "Spicy Tuna Roll",
    description: "",
    price: "$6.99",
  },
  {
    id: "77",
    imageName: "img4.jpg",
    tag: "maki_sushi",
    name: "Spicy Hamachi Roll",
    description: "",
    price: "$6.59",
  },
  {
    id: "78",
    imageName: "img1.jpg",
    tag: "maki_sushi",
    name: "Spicy Salmon Roll",
    description: "",
    price: "$6.99",
  },
  {
    id: "79",
    imageName: "img2.jpg",
    tag: "maki_sushi",
    name: "Spicy Scallop Roll",
    description: "",
    price: "$6.99",
  },
  {
    id: "80",
    imageName: "img3.jpg",
    tag: "maki_sushi",
    name: "Spicy Tako Roll",
    description: "(Spicy octopus roll)",
    price: "$6.99",
  },
  {
    id: "81",
    imageName: "img4.jpg",
    tag: "maki_sushi",
    name: "Shrimp Tempura Roll",
    description: "",
    price: "$7.99",
  },
];
