export default [
  {
    id: "92",
    imageName: "img2.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Ama Ebi",
    description: "Sweet Shrimp",
    price: "Nigiri $7.59",
  },
  {
    id: "93",
    imageName: "img3.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Ebi",
    description: "Shrimp",
    price: "Nigiri $4.99/Sashimi $9.99",
  },
  {
    id: "94",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Escolar",
    description: "Escolar",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "95",
    imageName: "img1.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Hamachi",
    description: "Yellow Tail",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "96",
    imageName: "img2.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Hirame",
    description: "Halibut",
    price: "Nigiri $7.59/Sashimi $15.99",
  },
  {
    id: "97",
    imageName: "img3.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Hotategai",
    description: "Japanese Scallop",
    price: "Nigiri $7.59/Sashimi $15.99",
  },
  {
    id: "98",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Ika",
    description: "Squid",
    price: "Nigiri $7.59/Sashimi $15.99",
  },
  {
    id: "99",
    imageName: "img1.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Ikura",
    description: "Salmon Egg",
    price: "Nigiri $7.99",
  },
  {
    id: "100",
    imageName: "img2.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Kani",
    description: "Snow Crab",
    price: "Nigiri $6.99",
  },
  {
    id: "101",
    imageName: "img3.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Kanpachi",
    description: "Amber Jack",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "101",
    imageName: "img3.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Kurodai",
    description: "Black sea bream",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "102",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Maguro",
    description: "Tuna",
    price: "Nigiri $7.99/Sashimi $15.99",
  },
    {
    id: "102",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Saba",
    description: "Japanese Mackerel",
    price: "Nigiri $4.99/Sashimi $9.99",
  },
  {
    id: "103",
    imageName: "img2.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Sake",
    description: "Salmon",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "104",
    imageName: "img3.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Smoked Sake",
    description: "Smoked Salmon",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "105",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Shiro Maguro",
    description: "Albacore Tuna",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "106",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Suzuki",
    description: "Seabass",
    price: "Nigiri $6.99/Sashimi $13.99",
  },
  {
    id: "107",
    imageName: "img2.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Tako",
    description: "Octopus",
    price: "Nigiri $7.99/Sashimi $15.99",
  },
  {
    id: "107",
    imageName: "img2.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Tamago",
    description: "Egg Omelet",
    price: "Nigiri $4.59/Sashimi $9.99",
  },
  {
    id: "108",
    imageName: "img3.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Tobiko",
    description: "Flying Fish Egg",
    price: "Nigiri $7.99",
  },
  {
    id: "109",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Unagi",
    description: "Fresh Water Eel",
    price: "Nigiri $7.99/Sashimi $15.99",
  },
  {
    id: "110",
    imageName: "img4.jpg",
    tag: "nigiri&sashimi_combo",
    name: "Uni",
    description: "Sea Urchin",
    price: "market price & availability",
  },
];
