export default [
  {
    id: "82",
    imageName: "img1.jpg",
    tag: "veggie_rolls",
    name: "Veggie Tempura Roll",
    description: "",
    price: "$5.79",
  },
  {
    id: "83",
    imageName: "img2.jpg",
    tag: "veggie_rolls",
    name: "Avacado Roll",
    description: "",
    price: "$3.79",
  },
  {
    id: "84",
    imageName: "img3.jpg",
    tag: "veggie_rolls",
    name: "Kappa Maki",
    description: "(Cucumber Roll)",
    price: "$3.79",
  },
  {
    id: "85",
    imageName: "img4.jpg",
    tag: "veggie_rolls",
    name: "Asparagus Roll",
    description: "",
    price: "$3.79",
  },
  {
    id: "85",
    imageName: "img1.jpg",
    tag: "veggie_rolls",
    name: "Summer Roll",
    description: "Asparagus, pickled carrots, green mix, avocado sprouts & cucumber wrapped in soy paper with eel sauce",
    price: "$7.25",
  },
  {
    id: "86",
    imageName: "img2.jpg",
    tag: "veggie_rolls",
    name: "Ichiban Roll",
    description: "Grilled veggies in soy paper topped with eel sauce",
    price: "$7.25",
  },
];
